spring.application.name=inventory-service
server.port=${SERVER_PORT:8081}
spring.data.redis.host=${REDIS_HOST:127.0.0.1}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2s
fault.mode=${FAULT_MODE:none}
fault.redis-timeout-seconds=${FAULT_REDIS_TIMEOUT_SECONDS:3}
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
demo.project=${PROJECT_TAG:mall-demo}
demo.logging.pattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg | source=java_selfheal_demo service=${DD_SERVICE:inventory-service} env=${DD_ENV:demo} version=${DD_VERSION:1.0.0} project=${demo.project} trace_id=%X{dd.trace_id} span_id=%X{dd.span_id} key_request=%X{key_request} biz_request_id=%X{biz_request_id} language=%X{language} fault_id=%X{fault_id} fault_layer=%X{fault_layer} fault_kind=%X{fault_kind} fault_target=%X{fault_target} process_id=%X{process_id} host_process_id=%X{host_process_id} container_process_id=%X{container_process_id} host=%X{host} host_name=%X{host_name} pod_name=%X{pod_name} pod_namespace=%X{pod_namespace} container_name=%X{container_name} container_id=%X{container_id}%n
logging.pattern.console=${demo.logging.pattern}
logging.pattern.file=${demo.logging.pattern}
